PROGRAM DIAMOND;
USES CRT;
VAR
   A,B,C,D : INTEGER;
   E,F,G,H : INTEGER;
   X : STRING;
BEGIN
     X := 'Y';
     WHILE (X = 'Y') DO
     BEGIN
     CLRSCR;

     WRITELN('PROGRAM PEMBUAT DIAMOND');
     WRITELN('=================================');
     WRITELN('');

     WRITE('MASUKKAN TINGGI SEGITIGA: ');
     READ(A);
     READLN(E);

     FOR B := 0 TO (A-1) DO
     BEGIN
          FOR C :=
     END;


     WRITE('BUAT DIAMOND LAGI? (Y/T): ');
     READLN(X);
     END;
END.